
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author knc
 */
public class GUI_02 extends javax.swing.JFrame {

    /**
     * Creates new form Employee_GUI
     */
    public GUI_02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtfeil1 = new javax.swing.JTextArea();
        txtTest2 = new javax.swing.JTextField();

        jMenu2.setText("jMenu2");

        jMenuItem3.setBackground(new java.awt.Color(255, 51, 51));
        jMenuItem3.setText(" ");
        jMenuItem3.setOpaque(true);
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jPopupMenu1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtfeil1.setColumns(20);
        txtfeil1.setRows(5);
        txtfeil1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfeil1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfeil1FocusLost(evt);
            }
        });
        txtfeil1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtfeil1InputMethodTextChanged(evt);
            }
        });
        txtfeil1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfeil1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtfeil1);

        txtTest2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTest2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTest2FocusLost(evt);
            }
        });
        txtTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTest2ActionPerformed(evt);
            }
        });
        txtTest2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTest2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(txtTest2))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtfeil1.append("Active");
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        txtfeil1.append("close");
        JOptionPane.showMessageDialog(this, "Clsoe");
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
    
    private void txtTest2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTest2FocusGained
                txtfeil1.append("Gain user forcus\n");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTest2FocusGained

    private void txtTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTest2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTest2ActionPerformed

    private void txtTest2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTest2FocusLost
        txtfeil1.append("Dgree forecus\n");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTest2FocusLost

    private void txtTest2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTest2KeyPressed
        char c = evt.getKeyChar();
        txtfeil1.append("User input" +c + "key\n");        // TODO add your handling code here:
    }//GEN-LAST:event_txtTest2KeyPressed

    private void txtfeil1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfeil1KeyPressed
        return;
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeil1KeyPressed

    private void txtfeil1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtfeil1InputMethodTextChanged
        txtfeil1.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeil1InputMethodTextChanged

    private void txtfeil1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfeil1FocusLost
        return;
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeil1FocusLost

    private void txtfeil1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfeil1FocusGained
        return;
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfeil1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTest2;
    private javax.swing.JTextArea txtfeil1;
    // End of variables declaration//GEN-END:variables
}
