
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author knc
 */
public class Kem extends javax.swing.JFrame {

    /**
     * Creates new form Kem
     */
    public Kem() {
        initComponents();
        jResult.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jResult = new javax.swing.JPanel();
        ckVani = new javax.swing.JCheckBox();
        ckSocola = new javax.swing.JCheckBox();
        ckDau = new javax.swing.JCheckBox();
        ckBanana = new javax.swing.JCheckBox();
        ckApple = new javax.swing.JCheckBox();
        btnOrder = new javax.swing.JButton();
        lbResult = new javax.swing.JLabel();
        cbCash = new javax.swing.JRadioButton();
        cbMOMO = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Choose Kem u LIke Best");

        jResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ban Kem Day", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        ckVani.setText("Vani");

        ckSocola.setText("Socola");

        ckDau.setText("Dau");

        ckBanana.setText("Banana");

        ckApple.setText("Apple");

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbCash);
        cbCash.setText("Cash");

        buttonGroup1.add(cbMOMO);
        cbMOMO.setText("MOMO");

        javax.swing.GroupLayout jResultLayout = new javax.swing.GroupLayout(jResult);
        jResult.setLayout(jResultLayout);
        jResultLayout.setHorizontalGroup(
            jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultLayout.createSequentialGroup()
                        .addComponent(ckVani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(109, 109, 109))
                    .addGroup(jResultLayout.createSequentialGroup()
                        .addGroup(jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckApple)
                            .addComponent(ckBanana)
                            .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jResultLayout.createSequentialGroup()
                                .addGroup(jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jResultLayout.createSequentialGroup()
                                        .addComponent(ckDau)
                                        .addGap(120, 120, 120)
                                        .addComponent(btnOrder))
                                    .addComponent(ckSocola, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(233, 233, 233)
                                .addGroup(jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCash)
                                    .addComponent(cbMOMO))))
                        .addContainerGap(270, Short.MAX_VALUE))))
        );
        jResultLayout.setVerticalGroup(
            jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ckVani, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckSocola, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMOMO))
                .addGroup(jResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jResultLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ckDau))
                    .addGroup(jResultLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnOrder)))
                .addGap(18, 18, 18)
                .addComponent(ckBanana)
                .addGap(18, 18, 18)
                .addComponent(ckApple)
                .addGap(47, 47, 47)
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        String result = "You selected: ";
        int count=0;
        
        if(ckDau.isSelected()) 
            if(count ==0){
                result = result + "Kem dau";
                count++;
            }else
                result = result + ", Kem dau";
        if(ckVani.isSelected()) 
            if(count ==0){
                result = result + "Kem Vani";
                count++;
            }else
                result = result + ", Kem Vani";
        if(ckBanana.isSelected()) 
            if(count ==0){
                result = result + "Kem Banana";
                count++;
            }else
                result = result + ", Kem Banana";
        if(ckApple.isSelected()) 
            if(count ==0){
                result = result + "Kem Apple";
                count++;
            }else
                result = result + ", Kem Apple";
        if(ckSocola.isSelected()) 
            if(count ==0){
                result = result + "Kem Socola";
                count++;
            }else
                result = result + ", Kem Socola";
        
       lbResult.setText(result);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbCash;
    private javax.swing.JRadioButton cbMOMO;
    private javax.swing.JCheckBox ckApple;
    private javax.swing.JCheckBox ckBanana;
    private javax.swing.JCheckBox ckDau;
    private javax.swing.JCheckBox ckSocola;
    private javax.swing.JCheckBox ckVani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jResult;
    private javax.swing.JLabel lbResult;
    // End of variables declaration//GEN-END:variables
}
