/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thinhdph.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import thinhdph.dao.BikeDAO;
import thinhdph.dao.BrandDAO;
import thinhdph.dto.BikeDTO;
import thinhdph.dto.BrandDTO;
import thinhdph_utils.checkInput;

/**
 *
 * @author HungThinh
 */
public class MotorcycleManagement extends javax.swing.JPanel {

    Vector<String> headerBrand = new Vector<>();
    Vector dataBrand = new Vector(); 
    boolean addNewBrand = true;
    DefaultTableModel brandModel;
    
    Vector<String> headerBike = new Vector<>();
    Vector dataBike = new Vector();
    boolean addNewBike = true;
    DefaultTableModel bikeModel;
    
    public MotorcycleManagement() {
        initComponents();
        
        //Brand table header 
        headerBrand.add("BrandID");
        headerBrand.add("BrandName");
        headerBrand.add("Country");
        headerBrand.add("Description");
        
        brandModel = (DefaultTableModel) tblBrand.getModel();
        brandModel.setDataVector(dataBrand, headerBrand);
        
        
        //Bike table header 
        headerBike.add("MotocycleID");
        headerBike.add("Model");
        headerBike.add("Year");
        headerBike.add("Condition");
        headerBike.add("Price");
        headerBike.add("Quantity");
        headerBike.add("Warranty");
        headerBike.add("BrandID");
        
        bikeModel = (DefaultTableModel) tblBike.getModel();
        bikeModel.setDataVector(dataBike, headerBike);
        
        loadBrand();
        loadBike();
    }
    
    public void loadBrand() {
        try {
            BrandDAO brDAO = new BrandDAO();
            ArrayList<BrandDTO> listBrand = brDAO.loadBrand();//load 
            for(BrandDTO brDTO : listBrand) {
                Vector v = new Vector();
                v.add(brDTO.getBrandID());
                v.add(brDTO.getBrandName());
                v.add(brDTO.getBrandCountry());
                v.add(brDTO.getBrandDesciption());
                dataBrand.add(v);
            }
            tblBrand.updateUI();
            System.out.println(listBrand.size());
        } catch (Exception e) {
        }
    }
    
    public void loadBike() {
        try {
            BikeDAO bkDAO = new BikeDAO();
            ArrayList<BikeDTO> listBike = bkDAO.loadBike();
            for(BikeDTO bikeDTO : listBike) {
                Vector v = new Vector();
                v.add(bikeDTO.getMotocycleID());
                v.add(bikeDTO.getModel());
                v.add(bikeDTO.getYear());
                v.add(bikeDTO.getCondition());
                v.add(bikeDTO.getPrice());
                v.add(bikeDTO.getQuantity());
                v.add(bikeDTO.getWarranty());
                v.add(bikeDTO.getBrandID());
                dataBike.add(v);
            }
            //load combo box
            cbBrandName.removeAllItems();//make cb become null
            BrandDAO brDAO = new BrandDAO(); //call DAO 
            ArrayList<String> listBrandName = brDAO.getBrandNameForCbbox(); //load brandName in tblBIke into Arraylist
            for(String items : listBrandName) {//load each brandID into cbox
                cbBrandName.addItem(items);
            }
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBrand = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtBrandID = new javax.swing.JTextField();
        txtBrandName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBrandCountry = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBrandDes = new javax.swing.JTextField();
        btnBrandSave = new javax.swing.JButton();
        btnBrandAdd = new javax.swing.JButton();
        btnBrandDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBike = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMotoID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCondition = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtWarranty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbBrandName = new javax.swing.JComboBox<>();
        btnAddMoto = new javax.swing.JButton();
        btnDeleteMoto = new javax.swing.JButton();
        btnSaveMoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "main part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 204))); // NOI18N

        tblBrand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrandMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBrand);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "detail part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Brand ID :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Brand Name :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Country :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Description :");

        btnBrandSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBrandSave.setText("Save");
        btnBrandSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandSaveActionPerformed(evt);
            }
        });

        btnBrandAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBrandAdd.setText("Add New");
        btnBrandAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandAddActionPerformed(evt);
            }
        });

        btnBrandDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBrandDelete.setText("Delete");
        btnBrandDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrandID)
                            .addComponent(txtBrandDes)
                            .addComponent(txtBrandName)
                            .addComponent(txtBrandCountry)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnBrandAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrandSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrandDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrandID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrandCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrandDes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 54, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrandSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrandAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrandDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 154, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Brand", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "main part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 0, 204))); // NOI18N

        tblBike.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBikeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBike);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "detail part", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("MotocycleID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Model :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Year :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Condition :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Price :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Quantity :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Warrranty :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Brand Name :");

        cbBrandName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAddMoto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAddMoto.setText("Add New");
        btnAddMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMotoActionPerformed(evt);
            }
        });

        btnDeleteMoto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDeleteMoto.setText("Delete");
        btnDeleteMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMotoActionPerformed(evt);
            }
        });

        btnSaveMoto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSaveMoto.setText("Save");
        btnSaveMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbBrandName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtWarranty))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCondition)
                            .addComponent(txtQuantity)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMotoID)
                            .addComponent(txtModel)
                            .addComponent(txtYear, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnAddMoto, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMotoID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveMoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Motocycle", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText(" MotorcycleManagement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblBrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrandMouseClicked
        addNewBrand = false;
        txtBrandID.setEditable(false);
        
        int selectedRow = tblBrand.getSelectedRow();
        String brandID =  tblBrand.getValueAt(selectedRow, 0).toString();
        String brandName = tblBrand.getValueAt(selectedRow, 1).toString();
        String brandCountry = tblBrand.getValueAt(selectedRow, 2).toString();
        String brandDes = tblBrand.getValueAt(selectedRow, 3).toString();

        txtBrandID.setText(brandID);
        txtBrandName.setText(brandName);
        txtBrandCountry.setText(brandCountry);
        txtBrandDes.setText(brandDes);
    }//GEN-LAST:event_tblBrandMouseClicked

    private void btnBrandAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandAddActionPerformed
        addNewBrand = true;
        txtBrandID.setEditable(true);
        txtBrandID.setText("");
        txtBrandCountry.setText("");
        txtBrandDes.setText("");
        txtBrandName.setText("");
    }//GEN-LAST:event_btnBrandAddActionPerformed

    private void btnBrandSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandSaveActionPerformed
  
        BrandDAO brDAO = new BrandDAO();

        boolean duplicate = true;
        StringBuilder sb = new StringBuilder();
        sb.append(checkInput.checkID(txtBrandID.getText().trim()));
        sb.append(checkInput.checkName(txtBrandName.getText().trim()));
        sb.append(checkInput.checkCountry(txtBrandCountry.getText().trim()));
        sb.append(checkInput.checkDecription(txtBrandDes.getText().trim()));
        

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Notify", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        BrandDTO brDTO = new BrandDTO(txtBrandID.getText(), txtBrandName.getText(),
                                      txtBrandCountry.getText(), txtBrandDes.getText());
        
        if (addNewBrand == true) {
            try {
                duplicate = brDAO.checkDuplicate(txtBrandID.getText().trim());
                if (duplicate == false) {
                    brDAO.insertNewBrand(brDTO);
                    JOptionPane.showMessageDialog(this, "The brand " + txtBrandID.getText().trim() + " have been added!  ");
                    brandModel.setRowCount(0);
                    loadBrand();
                    loadBike();//load cbox
                    addNewBrand = false;
                } else {
                    JOptionPane.showMessageDialog(this, "This brand have been existed");
                }

            } catch (SQLException ex) {} 
              catch (ClassNotFoundException ex) {}
        } else {
            try {
                int choice = JOptionPane.showConfirmDialog(this, "Do you want to update brand " + txtBrandID.getText().trim() + " ?", "Notify", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    brDAO.updateBrand(brDTO);
                    JOptionPane.showMessageDialog(this, "Brand ID " + txtBrandID.getText().trim() + " have been updated!");
                    brandModel.setRowCount(0);
                    loadBrand();
                    loadBike();//load cbox
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnBrandSaveActionPerformed

    private void btnBrandDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandDeleteActionPerformed
        BrandDAO brDAO = new BrandDAO();
        String brandID = txtBrandID.getText().trim();
        try{
            int choice = JOptionPane.showConfirmDialog(this, "Do you want to detele brand " + txtBrandID.getText().trim() + " ?", "Notify", JOptionPane.YES_NO_OPTION);
            int numberOfBike = brDAO.count(brandID);
            if (choice == JOptionPane.YES_OPTION) {
                //count bike of tblBike by brandID
                if (numberOfBike <= 0) {//dont have any bike
                    brDAO.deteleBrand(txtBrandID.getText().trim());
                    JOptionPane.showMessageDialog(this, "Brand ID " + txtBrandID.getText().trim() + " have been deteled!");
                    brandModel.setRowCount(0);
                    loadBrand();
                } else //have 1 or more
                {
                    JOptionPane.showMessageDialog(this, "This brand have " + numberOfBike + " product. \nYou must delete all Motocycle with brand " + brandID + " to delete this brand!!!");
                }

            }
        } catch (SQLException ex) {ex.printStackTrace();} 
          catch (ClassNotFoundException ex) {ex.printStackTrace();}
    }//GEN-LAST:event_btnBrandDeleteActionPerformed

    private void btnAddMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMotoActionPerformed
        addNewBike = true;
        txtMotoID.setText("");
        txtMotoID.setEditable(true);
        txtModel.setText("");
        txtCondition.setText("");
        txtYear.setText("");
        txtPrice.setText("");
        txtQuantity.setText("");
        txtWarranty.setText("");
    }//GEN-LAST:event_btnAddMotoActionPerformed

    private void btnSaveMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMotoActionPerformed
//        BrandDAO brDAO = new BrandDAO();
        BikeDAO bkDAO = new BikeDAO();
        BrandDAO brDAO = new BrandDAO();
        String brandID = cbBrandName.getSelectedItem().toString();
        String ID[] = brandID.split("-");
        brandID = ID[0];
        
        Boolean checkduplicateBikeID = true;
        
            StringBuilder sb = new StringBuilder();
            sb.append(checkInput.checkID(txtMotoID.getText().trim()));
            sb.append(checkInput.checkModel(txtModel.getText().trim()));
            sb.append(checkInput.checkCondition(txtCondition.getText().trim()));
            sb.append(checkInput.checkPrice(txtPrice.getText().trim()));
            sb.append(checkInput.checkYear(txtYear.getText().trim()));
            sb.append(checkInput.checkQuantity(txtQuantity.getText().trim()));
            sb.append(checkInput.checkWarranty(txtWarranty.getText().trim()));
            
        
        
//            try {
////                brandID = brDAO.getBrandIDByName(cbBrandName.getSelectedItem().toString());
//                
//            } catch (SQLException ex) {
//                ex.printStackTrace();
//            } catch (ClassNotFoundException ex) {
//                ex.printStackTrace();
//            }

        BikeDTO bkDTO = new BikeDTO(txtMotoID.getText(), txtModel.getText(), txtYear.getText(),
                                    txtCondition.getText(), txtPrice.getText(), txtQuantity.getText(),
                                    txtWarranty.getText(), brandID);

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Notify", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (addNewBike == true) {
            try {
                checkduplicateBikeID = bkDAO.checkDuplicateBike(txtMotoID.getText().trim());
                
                if (checkduplicateBikeID == false) {
                    bkDAO.insertNewBike(bkDTO);
                    JOptionPane.showMessageDialog(this, "The bike " + txtMotoID.getText().trim() + " have been added!  ");
                    bikeModel.setRowCount(0);
                    loadBike();
                    addNewBike = false;
                } else {
                    JOptionPane.showMessageDialog(this, "This MotoID have been existed.");
                }

            } catch (SQLException ex) {
            } catch (ClassNotFoundException ex) {
            }
        } else { // when user click from table and want to update
            try {
                int choice = JOptionPane.showConfirmDialog(this, "Do you want to update bikeID " + txtMotoID.getText().trim() + " ?", "Notify", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    bkDAO.updateBike(bkDTO);
                    JOptionPane.showMessageDialog(this, "Bike ID " + txtMotoID.getText().trim() + " have been updated!");
                    bikeModel.setRowCount(0);
                    loadBike();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        }
  
    }//GEN-LAST:event_btnSaveMotoActionPerformed

    private void tblBikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBikeMouseClicked
        addNewBike = false;
        txtMotoID.setEditable(false);
        BrandDAO brDAO = new BrandDAO();
        
        int selectedRow = tblBike.getSelectedRow();
        String bikeID = tblBike.getValueAt(selectedRow, 0).toString();
        String model = tblBike.getValueAt(selectedRow, 1).toString();
        String year = tblBike.getValueAt(selectedRow, 2).toString();
        String condition = tblBike.getValueAt(selectedRow, 3).toString();
        String price = tblBike.getValueAt(selectedRow, 4).toString();
        String quantity = tblBike.getValueAt(selectedRow, 5).toString();
        String warranty = tblBike.getValueAt(selectedRow, 6).toString();
        String brandID = tblBike.getValueAt(selectedRow, 7).toString();
        
        txtMotoID.setText(bikeID);
        txtModel.setText(model);
        txtYear.setText(year);
        txtCondition.setText(condition);
        txtPrice.setText(price);
        txtQuantity.setText(quantity);
        txtWarranty.setText(warranty);
//        cbBrandName.removeAllItems();
        //getItemName for combobox
        try {
            String itemCbbox = brDAO.getBrandNameByID(brandID);
            cbBrandName.setSelectedItem(itemCbbox);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_tblBikeMouseClicked

    private void btnDeleteMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMotoActionPerformed
        BikeDAO bkDAO = new BikeDAO();
        String motoID = txtMotoID.getText().trim();
        try{
        int choice = JOptionPane.showConfirmDialog(this, "Do you want to detele moto " +txtMotoID.getText().trim()+" ?", "Notify", JOptionPane.YES_NO_OPTION);       
                if (choice == JOptionPane.YES_OPTION) {

                bkDAO.deteleBike(txtMotoID.getText().trim());
                JOptionPane.showMessageDialog(this, "Moto ID " + txtMotoID.getText().trim() + " have been deteled!");
                bikeModel.setRowCount(0);
                loadBike();
                } else {

                }
                
        } catch (SQLException ex) {ex.printStackTrace();} 
          catch (ClassNotFoundException ex) {ex.printStackTrace();}

    }//GEN-LAST:event_btnDeleteMotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMoto;
    private javax.swing.JButton btnBrandAdd;
    private javax.swing.JButton btnBrandDelete;
    private javax.swing.JButton btnBrandSave;
    private javax.swing.JButton btnDeleteMoto;
    private javax.swing.JButton btnSaveMoto;
    private javax.swing.JComboBox<String> cbBrandName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblBike;
    private javax.swing.JTable tblBrand;
    private javax.swing.JTextField txtBrandCountry;
    private javax.swing.JTextField txtBrandDes;
    private javax.swing.JTextField txtBrandID;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtMotoID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtWarranty;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
