/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.tblItem;
import DAO.tblSupliers;
import DTO.Items;
import DTO.Suppliers;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author knc
 */
public class ManagerUI extends javax.swing.JFrame {

    tblItem modelItem;
    tblSupliers modelSup;
    final int SUCCESS = 1;
    boolean addNewItem = true;
    boolean addNewSup = true;
    boolean deleteSup = true;
    boolean deleteItem = true;

    /**
     * Creates new form ManagerUI
     */
    public ManagerUI() throws Exception {
        initComponents();
        modelSup = new tblSupliers();
        tblSuppliers.setModel(modelSup.getModelSup());
        modelItem = new tblItem();
        tblItems.setModel(modelItem.getModelItem());

        try {
            cbSuppliers.setModel(new DefaultComboBoxModel<>(modelSup.getListSuppliersComboBox()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void clearInforItemTable() {
        txtItemCode.setText("");
        txtItemName.setText("");
        cbSuppliers.setSelectedItem(null);
        txtUnit.setText("");
        txtPrice.setText("");
        chkSupplying.setSelected(false);
    }

    void clearInforSupTable() {
        txtSupCode.setText("");
        txtSupName.setText("");
        txtAddress.setText("");
        chkColloborating.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSupName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtSupCode = new javax.swing.JTextField();
        chkColloborating = new javax.swing.JCheckBox();
        btnSupNew = new javax.swing.JButton();
        btnSupDelete = new javax.swing.JButton();
        btnSupSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbCode = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbSupplier = new javax.swing.JLabel();
        lbUnit = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbSupplying = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        chkSupplying = new javax.swing.JCheckBox();
        cbSuppliers = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplier's details"));

        jLabel1.setText("Code");

        jLabel2.setText("Address");

        jLabel3.setText("Colloboration");

        jLabel4.setText("Name");

        btnSupNew.setText("New");
        btnSupNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupNewActionPerformed(evt);
            }
        });

        btnSupDelete.setText("Delete");
        btnSupDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupDeleteActionPerformed(evt);
            }
        });

        btnSupSave.setText("Save");
        btnSupSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSupCode, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(chkColloborating))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(btnSupNew)
                            .addGap(44, 44, 44)
                            .addComponent(btnSupDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSupSave))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtSupCode)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSupName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkColloborating, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupNew)
                    .addComponent(btnSupDelete)
                    .addComponent(btnSupSave))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSuppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuppliersMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblSuppliersMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblSuppliers);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Suppliers", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Details"));

        lbCode.setText("Item code:");

        lbName.setText("Item name:");

        lbSupplier.setText("Supplier:");

        lbUnit.setText("Unit:");

        lbPrice.setText("Price");

        lbSupplying.setText("Supplying");

        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });

        cbSuppliers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtItemCode))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbName)
                        .addGap(7, 7, 7)
                        .addComponent(txtItemName))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbUnit)
                        .addGap(39, 39, 39)
                        .addComponent(txtUnit))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbPrice)
                        .addGap(39, 39, 39)
                        .addComponent(txtPrice))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbSupplying)
                        .addGap(18, 18, 18)
                        .addComponent(chkSupplying)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbSupplier)
                        .addGap(18, 18, 18)
                        .addComponent(cbSuppliers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCode)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSupplier)
                    .addComponent(cbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUnit)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSupplying)
                    .addComponent(chkSupplying))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnNew.setText("AddNew");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblItemsMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblItems);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnNew)
                        .addGap(47, 47, 47)
                        .addComponent(btnDelete)
                        .addGap(28, 28, 28)
                        .addComponent(btnSave)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addGap(0, 131, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Items", jPanel1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtItemCode.setEditable(true);
        clearInforItemTable();
        addNewItem = true;
        deleteItem = false;
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (!modelItem.validDate(txtItemCode.getText().trim(), txtItemName.getText().trim(), txtUnit.getText().trim(), txtPrice.getText().trim(), cbSuppliers.getSelectedItem())) {
            return;
        }
        if (addNewSup) {
            try {
                if (!modelItem.validDateCodeItem(txtItemCode.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Dublicate ITEMCODE at " + txtItemCode.getText().trim());
                    return;
                }
                Items it = new Items(txtItemCode.getText().toUpperCase().trim(), txtItemName.getText().trim(), txtUnit.getText().trim(), Float.parseFloat(txtPrice.getText().trim()), chkSupplying.isSelected(), modelItem.loadSupCodeIntoItems(cbSuppliers.getSelectedItem().toString()));
                if (modelItem.Insert(it) == SUCCESS) {
                    modelItem.getModelItem().getList().add(it);
                }
                addNewSup = false;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                int selectedRow = tblItems.getSelectedRow();
                if (selectedRow < 0) {
                    JOptionPane.showMessageDialog(this, "Choose ROW to Edit");
                    return;
                }
                Items itOld = modelItem.getModelItem().getList().get(selectedRow);
                Items itNew = new Items(txtItemCode.getText().toUpperCase().trim(), txtItemName.getText().trim(), txtUnit.getText().trim(), Float.parseFloat(txtPrice.getText().trim()), chkSupplying.isSelected(), modelItem.loadSupCodeIntoItems(cbSuppliers.getSelectedItem().toString()));
                

                if (modelItem.Save(itNew) == SUCCESS) {
                    itOld.setIteamName(itNew.getIteamName());
                    itOld.setPrice(itNew.getPrice());
                    itOld.setUnit(itNew.getUnit());
                    itOld.setSupCode(itNew.getSupCode());
                    itOld.setSupplying(itNew.isSupplying());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tblItems.updateUI();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int selectedRow = tblItems.getSelectedRow();
            if (selectedRow < 0 || deleteItem == false) {
                JOptionPane.showMessageDialog(this, "Choose the ROW to Delete");
                return;
            }
            int r = JOptionPane.showConfirmDialog(this, "Do you want to Delete this Item?");
            if (r == JOptionPane.YES_OPTION) {
                Items it = modelItem.getModelItem().getList().get(selectedRow);
                if (modelItem.Delete(it) == SUCCESS) {
                    deleteItem = false;
                    modelItem.getModelItem().getList().remove(it);
                    JOptionPane.showMessageDialog(this, "Deleted");
                    clearInforItemTable();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tblItems.updateUI();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSupNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupNewActionPerformed
        txtSupCode.setEditable(true);
        clearInforSupTable();
        addNewSup = true;
        deleteSup = false;
    }//GEN-LAST:event_btnSupNewActionPerformed

    private void btnSupSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupSaveActionPerformed
         if (!modelSup.validDate(txtSupCode.getText().trim(), txtSupName.getText().trim(), txtAddress.getText().trim())) {
            return;
        }
        if (addNewSup) {
            try {
                if (!modelSup.validDateCodeSupplier(txtSupCode.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Dublicate SUPCODE at " + txtSupCode.getText().trim());
                    return;
                }
                Suppliers sup = new Suppliers(txtSupCode.getText().trim(), txtSupName.getText().trim(), txtAddress.getText().trim(), chkColloborating.isSelected());
                if (modelSup.Insert(sup) == SUCCESS) {
                    modelSup.getModelSup().getList().add(sup);
                    modelSup.getListSuppliersComboBox().add(sup.getSupCode() + " - " + sup.getSupName());
                }
                addNewSup = false;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            try {
                int selectedRow = tblSuppliers.getSelectedRow();
                if (selectedRow < 0) {
                    JOptionPane.showMessageDialog(this, "Choose ROW to Edit");
                    return;
                }

                Suppliers supNew = new Suppliers(txtSupCode.getText().trim(), txtSupName.getText().trim(), txtAddress.getText().trim(), chkColloborating.isSelected());
                Suppliers supOld = modelSup.getModelSup().getList().get(selectedRow);

                if (modelSup.Save(supNew) == SUCCESS) {
                    modelSup.getListSuppliersComboBox().remove(supOld.getSupCode() + " - " + supOld.getSupName());
                    supOld.setSupName(supNew.getSupName());
                    supOld.setAddress(supNew.getAddress());
                    supOld.setColloborating(supNew.isColloborating());
                    modelSup.getListSuppliersComboBox().add(supNew.getSupCode() + " - " + supNew.getSupName());

                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        modelItem.getModelItem().loadSuppliersComboBox();
        cbSuppliers.setModel(new DefaultComboBoxModel<>(modelSup.getListSuppliersComboBox()));
        tblSuppliers.updateUI();
    }//GEN-LAST:event_btnSupSaveActionPerformed

    private void btnSupDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupDeleteActionPerformed
        try {
            int selectedRow = tblSuppliers.getSelectedRow();
            if (selectedRow < 0 || deleteSup == false) {
                JOptionPane.showMessageDialog(this, "Choose the ROW to Delete");
                return;
            }
            int r = JOptionPane.showConfirmDialog(this, "Do you want to Delete this Supplier?");
            if (r == JOptionPane.YES_OPTION) {
                Suppliers sup = modelSup.getModelSup().getList().get(selectedRow);
                if (modelSup.Delete(sup) == SUCCESS) {
                    deleteItem = false;
                    modelSup.getModelSup().getList().remove(sup);
                    modelSup.getListSuppliersComboBox().remove(sup.getSupCode() + " - " + sup.getSupName());
                    JOptionPane.showMessageDialog(this, "Deleted");
                    cbSuppliers.setModel(new DefaultComboBoxModel<>(modelSup.getListSuppliersComboBox()));
                    clearInforSupTable();
                    modelItem.getModelItem().loadSuppliersComboBox();
                    tblSuppliers.updateUI();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tblSuppliers.updateUI();
    }//GEN-LAST:event_btnSupDeleteActionPerformed

    private void tblSuppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuppliersMouseClicked
        int selectRow = tblSuppliers.getSelectedRow();
        Suppliers supplier = modelSup.getModelSup().getList().get(selectRow);
        txtSupCode.setText(supplier.getSupCode());
        txtSupCode.setEditable(false);
        txtSupName.setText(supplier.getSupName());
        txtAddress.setText("" + supplier.getAddress());
        chkColloborating.setSelected(supplier.isColloborating());
        addNewSup = false;
        deleteSup = false;      
    }//GEN-LAST:event_tblSuppliersMouseClicked

    private void tblSuppliersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuppliersMouseReleased
        int row = tblSuppliers.getSelectedRow();
        int col = tblSuppliers.getSelectedColumn();
        tblSuppliers.getCellEditor(row, col).cancelCellEditing();
    }//GEN-LAST:event_tblSuppliersMouseReleased

    private void tblItemsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseReleased
        int row = tblItems.getSelectedRow();
        int col = tblItems.getSelectedColumn();
        tblItems.getCellEditor(row, col).cancelCellEditing();
    }//GEN-LAST:event_tblItemsMouseReleased

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
        int selectRow = tblItems.getSelectedRow();
        Items it = modelItem.getModelItem().getList().get(selectRow);
        txtItemCode.setText(it.getIteamCode());
        txtItemCode.setEditable(false);
        txtItemName.setText(it.getIteamName());
        txtPrice.setText(it.getPrice() + "");
        txtUnit.setText(it.getUnit());
        chkSupplying.setSelected(it.isSupplying());
        cbSuppliers.setSelectedItem((it.getSupCode() + " - ") + modelSup.getSupNameComboBox(it.getSupCode()));
        addNewSup = false;
        deleteSup = false;     
    }//GEN-LAST:event_tblItemsMouseClicked

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManagerUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ManagerUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSupDelete;
    private javax.swing.JButton btnSupNew;
    private javax.swing.JButton btnSupSave;
    private javax.swing.JComboBox<String> cbSuppliers;
    private javax.swing.JCheckBox chkColloborating;
    private javax.swing.JCheckBox chkSupplying;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCode;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbSupplier;
    private javax.swing.JLabel lbSupplying;
    private javax.swing.JLabel lbUnit;
    private javax.swing.JTable tblItems;
    private javax.swing.JTable tblSuppliers;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSupCode;
    private javax.swing.JTextField txtSupName;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
